modfiy check_disk while X

diff --git a/eyou/mail/eyou_ha_version1.0/eyou_mail_shell/eyou_mail_mysql b/eyou/mail/eyou_ha_version1.0/eyou_mail_shell/eyou_mail_mysql
--- a/eyou/mail/eyou_ha_version1.0/eyou_mail_shell/eyou_mail_mysql
+++ b/eyou/mail/eyou_ha_version1.0/eyou_mail_shell/eyou_mail_mysql
@@ -35,12 +35,18 @@ eyou_status () {
 #	$EYOU_MAIL watch $EYOU_SYS_NAME >>${EYOU_SER_FILE_CONF}_fail 2>&1
 	[ -f $EYOU_SYS_PID_FILE ] || exit 1
 #	if $EYOU_MAIL watch $EYOU_SYS_NAME > /dev/null 2>&1;then
-	$EYOU_MAIL watch $EYOU_SYS_NAME > /dev/null 2>&1
+#	$EYOU_MAIL watch $EYOU_SYS_NAME > /dev/null 2>&1
+	$EYOU_MAIL watch $EYOU_SYS_NAME 1 > /dev/null 2>>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
 	exit_val=$?
-	while [ "$exit_val" == "" ];do $EYOU_MAIL watch $EYOU_SYS_NAME > /dev/null 2>&1;exit_val=$?;done
+	[ "$(cat ${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME})" == "" ] && rm -rf ${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
+#	while [ "$exit_val" == "" ];do $EYOU_MAIL watch $EYOU_SYS_NAME > /dev/null 2>&1;exit_val=$?;done
+	while [ "$exit_val" == "" ];do $EYOU_MAIL watch $EYOU_SYS_NAME 1 > /dev/null 2>>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME};exit_val=$?;done
 	if [ "$exit_val" == "0" ];then
 		exit_val=0
 	else
+		echo '======'>>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
+		echo $exit_val >>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
+		echo '======'>>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
 		echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME status fail message... " >> ${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
 		$EYOU_MAIL watch $EYOU_SYS_NAME >> ${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME} 2>&1
 		exit_val=$?
